//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMime
    {
        public CatMime()
        {
            this.CatMimeExtension = new HashSet<CatMimeExtension>();
            this.Media = new HashSet<Media>();
        }
    
        public int CatMimeId { get; set; }
        public string Mime { get; set; }
        public string Description { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual ICollection<CatMimeExtension> CatMimeExtension { get; set; }
        public virtual ICollection<Media> Media { get; set; }
    }
}
