//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMimeExtension
    {
        public int MimeExtensionId { get; set; }
        public int CatMimeId { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual CatMime CatMime { get; set; }
    }
}
