//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatScreenSize
    {
        public CatScreenSize()
        {
            this.Screen = new HashSet<Screen>();
        }
    
        public int CatScreenSizeId { get; set; }
        public int SizeX { get; set; }
        public int SizeY { get; set; }
        public string Description { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual ICollection<Screen> Screen { get; set; }
    }
}
