//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.ChannelSchedule = new HashSet<ChannelSchedule>();
            this.ScreenSchedule = new HashSet<ScreenSchedule>();
        }
    
        public long ChannelId { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual ICollection<ChannelSchedule> ChannelSchedule { get; set; }
        public virtual ICollection<ScreenSchedule> ScreenSchedule { get; set; }
    }
}
