//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.Device = new HashSet<Device>();
            this.ScreenSchedule = new HashSet<ScreenSchedule>();
        }
    
        public long ScreenId { get; set; }
        public string Name { get; set; }
        public int CatScreenSizeId { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CatScreenSize CatScreenSize { get; set; }
        public virtual ICollection<Device> Device { get; set; }
        public virtual ICollection<ScreenSchedule> ScreenSchedule { get; set; }
    }
}
