//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwChannel
    {
        public long ChannelId { get; set; }
        public string Name { get; set; }
        public string LstMedias { get; set; }
        public string DatetimeChannel { get; set; }
        public string UserName { get; set; }
    }
}
