//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDevice
    {
        public int DeviceId { get; set; }
        public string Ip { get; set; }
        public string HostName { get; set; }
        public string ScreenName { get; set; }
        public string DatetimeDevice { get; set; }
        public string UserName { get; set; }
    }
}
