//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwMedia
    {
        public long MediaId { get; set; }
        public string LogicName { get; set; }
        public long Size { get; set; }
        public string Type { get; set; }
        public Nullable<long> Length { get; set; }
        public string Url { get; set; }
        public string DatetimeMedia { get; set; }
        public string UserName { get; set; }
    }
}
