//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwScreen
    {
        public long ScreenId { get; set; }
        public string Name { get; set; }
        public string LstChannels { get; set; }
        public string DatetimeScreen { get; set; }
        public string ScreenSize { get; set; }
        public string UserName { get; set; }
    }
}
