//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignageDigitalPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignageDigitalPortal.Resources.ResShared", typeof(ResShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uno o más campos inválidos. Por favor revise sus datos e intente de nuevo..
        /// </summary>
        public static string ERROR_INVALID_MODEL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se sucitó un problema de red. Por favor revise que esté conectado a Internet e intente de nuevo..
        /// </summary>
        public static string ERROR_NOT_NETWORK {
            get {
                return ResourceManager.GetString("ERROR_NOT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita ingresar al portal antes de subir un archivo..
        /// </summary>
        public static string ERROR_NOTAUTHENTICATED_USER {
            get {
                return ResourceManager.GetString("ERROR_NOTAUTHENTICATED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido..
        /// </summary>
        public static string ERROR_UNKOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue guardado de forma exitosa.
        /// </summary>
        public static string INFO_REGISTER_SAVED {
            get {
                return ResourceManager.GetString("INFO_REGISTER_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando su petición....
        /// </summary>
        public static string TITLE_PROCESSING {
            get {
                return ResourceManager.GetString("TITLE_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro fallido.
        /// </summary>
        public static string TITLE_REGISTER_FAILED {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string TITLE_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido:.
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
    }
}
